INSERT INTO departments (department_name)
VALUES 
("Kitchen"), 
("Waitstaff"),
("Bartending"),
("Human Resources"),
("Accounting"),
("Management"),
("Events");

INSERT INTO roles (title, salary, department_id)
VALUES 
("Chef", 65000, 6),
("Sous Chef", 60000, 1),
("Cook", 35000, 1),
("Waiter", 30000, 2),
("Bartender", 35000, 3), 
("Customer Service", 35000, 4),
("Event Coordinator", 45000, 7), 
("HR Manager", 55000, 6),
("Marketing Specialist", 50000, 5),
("Accountant", 55000, 5), 
("Restaurant Manager", 70000, 6);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES 
("John", "Smith", 11, NULL),
("James", "Brown", 2, 10),
("Emily", "Johnson", 3, 10),
("Sarah", "Miller", 4, 1), 
("Rachel", "Davis", 8, NULL),
("Michael", "Wilson", 6, 5),
("Jessica", "Taylor", 7, 5),
("David", "Anderson", 5, 1), 
("Sophia", "Thomas", 9, 5), 
("Liam", "White", 1, NULL),
("Oliver", "Harris", 2, 10), 
("Ava", "Martin", 3, 10), 
("Lucas", "Jackson", 5, 1), 
("Isabella", "Thompson", 4, 1), 
("Mason", "Martinez", 6, 5), 
("Emma", "Robinson", 7, 5), 
("Logan", "Clark", 3, 10), 
("Mia", "Rodriguez", 9, 5), 
("Elijah", "Lewis", 3, 10), 
("Amelia", "Walker", 2, 10), 
("Benjamin", "Hall", 3, 10), 
("Harper", "Allen", 10, 5), 
("Ethan", "Young", 3, 10), 
("Madison", "Hernandez", 6, 5), 
("William", "King", 7, 5), 
("Charlotte", "Wright", 4, 1), 
("Daniel", "Lopez", 9, 5), 
("Aiden", "Hill", 3, 10), 
("Ella", "Scott", 2, 10), 
("Matthew", "Green", 4, 1), 
("Abigail", "Adams", 5, 1), 
("Lucy", "Baker", 6, 5), 
("Alexander", "Gonzalez", 6, 5), 
("Victoria", "Nelson", 7, 5), 
("Jack", "Carter", 3, 10);
